services:

  flask:
    build:
      context: ./flask
    restart: always
    env_file:
      - .env
    volumes:
      - ./flask:/app
      - ./config/ai_config.json:/opt/edu-ai/ai_config.json:ro
    environment:
      AI_CONFIG_PATH: /opt/edu-ai/ai_config.json
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - web
      - internal
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: gunicorn -w 16 -b :8000 app:app

  mysql:
    image: mysql:8.2
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: edu
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "16g"
        reservations:
          memory: "8g"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data
    networks:
      - internal

  rasa:
    build:
      context: ./rasa/
    volumes:
      - ./rasa:/app
      - ./config/ai_config.json:/opt/edu-ai/ai_config.json:ro
    env_file:
      - .env
    environment:
      AI_CONFIG_PATH: /opt/edu-ai/ai_config.json
    command:
      - run
      - --enable-api
    depends_on:
      - redis
      - action_server
    networks:
      - internal
      - web
    ports:
      - "5005:5005"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.rasa.rule=Host(`bot.edu-ai.eu`)"
      - "traefik.http.routers.rasa.entrypoints=web"
      - "traefik.http.services.rasa.loadbalancer.server.port=5005"
      # CORS headers
      - "traefik.http.middlewares.rasa-cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS,PUT,DELETE"
      - "traefik.http.middlewares.rasa-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.rasa-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.rasa-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.rasa-cors.headers.addvaryheader=true"
      - "traefik.http.middlewares.rasa-cors.headers.accesscontrolallowcredentials=true"
      # Apply middleware
      - "traefik.http.routers.rasa.middlewares=rasa-cors@docker"

  action_server:
    build:
      context: ./rasa/actions
      dockerfile: Dockerfile
    volumes:
      - ./rasa/actions:/app/actions
      - ./config/ai_config.json:/opt/edu-ai/ai_config.json:ro
    env_file:
      - .env
    environment:
      AI_CONFIG_PATH: /opt/edu-ai/ai_config.json
    networks:
      - internal
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.action-server.rule=Host(`bot.edu-ai.eu`) && PathPrefix(`/webhook`)"
      - "traefik.http.routers.action-server.entrypoints=web"
      - "traefik.http.services.action-server.loadbalancer.server.port=5055"
      - "traefik.http.services.action-server.loadbalancer.sticky.cookie=true"
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  worker:
    build:
      context: ./rasa/actions
      dockerfile: Dockerfile-celery
    restart: always
    networks:
      - internal
    env_file:
      - .env
    volumes:
      - ./rasa/actions:/app
      - ./config/ai_config.json:/opt/edu-ai/ai_config.json:ro
    environment:
      AI_CONFIG_PATH: /opt/edu-ai/ai_config.json
    command: celery -A celery_app.celery worker -l debug -c 4 -Ofair --uid=nobody --gid=nogroup
    depends_on:
      - rabbit

  worker2:
    build:
      context: ./rasa/actions
      dockerfile: Dockerfile-celery
    restart: always
    networks:
      - internal
    env_file:
      - .env
    volumes:
      - ./rasa/actions:/app
      - ./config/ai_config.json:/opt/edu-ai/ai_config.json:ro
    environment:
      AI_CONFIG_PATH: /opt/edu-ai/ai_config.json
    command: celery -A celery_app.celery worker -l debug -c 4 -Ofair --uid=nobody --gid=nogroup
    depends_on:
      - rabbit

  worker3:
    build:
      context: ./rasa/actions
      dockerfile: Dockerfile-celery
    restart: always
    networks:
      - internal
    env_file:
      - .env
    volumes:
      - ./rasa/actions:/app
      - ./config/ai_config.json:/opt/edu-ai/ai_config.json:ro
    environment:
      AI_CONFIG_PATH: /opt/edu-ai/ai_config.json
    command: celery -A celery_app.celery worker -l debug -c 4 -Ofair --uid=nobody --gid=nogroup
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:latest
    networks:
      - internal
    restart: always
    ports:
      - "5672"
  
  fastapi:
    build:
      context: ./fastapi
    restart: always
    env_file:
      - .env
    environment:
      LANGSMITH_PROJECT: ${FASTAPI_LANGSMITH_PROJECT}
      AI_CONFIG_PATH: /opt/edu-ai/ai_config.json
    volumes:
      - ./fastapi:/code
      - ./config/ai_config.json:/opt/edu-ai/ai_config.json:ro
    networks:
      - web
      - internal
    ports:
      - "6767:80"

  webchat:
    build:
      context: ./webchat
    restart: always
    env_file:
      - .env
    environment:
      LANGSMITH_PROJECT: ${WEBCHAT_LANGSMITH_PROJECT}
      AI_CONFIG_PATH: /opt/edu-ai/ai_config.json
    volumes:
      - ./webchat:/code
      - ./config/ai_config.json:/opt/edu-ai/ai_config.json:ro
    networks:
      - web
      - internal
    depends_on:
      - redis
      - mysql
    ports:
      - "7070:80"
  
networks:
  web:
    external: true
  internal:
    external: false
