FROM python:3.14-slim-bookworm


WORKDIR /code


COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

CMD ["uvicorn", "code.main:app", "--app-dir", "/", "--host", "0.0.0.0", "--port", "80"]