FROM python:3.14-slim-bookworm


WORKDIR /code

ENV PYTHONPATH=/code:${PYTHONPATH}


COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

CMD ["uvicorn", "socketio_server:app", "--host", "0.0.0.0", "--port", "80"]