"""add fulltext index to events table

Revision ID: 05da9c445f05
Revises: 9a32ba5b2aa1
Create Date: 2025-07-15 13:44:12.427407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05da9c445f05'
down_revision = '9a32ba5b2aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_data_sender_id', 'events', ['data', 'sender_id'], unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_data_sender_id', table_name='events', mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###
