"""add_chat_message_model

Revision ID: 414f3b0a0448
Revises: 9bff59d2002e
Create Date: 2025-05-21 15:40:56.236235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '414f3b0a0448'
down_revision = '9bff59d2002e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_index('taskset_id', table_name='celery_tasksetmeta')
    op.drop_table('celery_tasksetmeta')
    op.drop_index('task_id', table_name='celery_taskmeta')
    op.drop_table('celery_taskmeta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_taskmeta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(), nullable=True),
    sa.Column('traceback', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('args', sa.BLOB(), nullable=True),
    sa.Column('kwargs', sa.BLOB(), nullable=True),
    sa.Column('worker', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('retries', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', mysql.VARCHAR(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('task_id', 'celery_taskmeta', ['task_id'], unique=False)
    op.create_table('celery_tasksetmeta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taskset_id', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('taskset_id', 'celery_tasksetmeta', ['taskset_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
