"""add_summary

Revision ID: 541c674cc1f6
Revises: 414f3b0a0448
Create Date: 2025-05-21 17:23:45.072131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541c674cc1f6'
down_revision = '414f3b0a0448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flagged_responses', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flagged_responses', 'summary')
    # ### end Alembic commands ###
