"""Add TeamInvitation model and creator_id to Team

Revision ID: 5e2c58f662e9
Revises: 05da9c445f05
Create Date: 2025-11-01 15:55:34.160299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2c58f662e9'
down_revision = '05da9c445f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invitations_invitee_email'), 'team_invitations', ['invitee_email'], unique=False)
    op.add_column('teams', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'creator_id')
    op.drop_index(op.f('ix_team_invitations_invitee_email'), table_name='team_invitations')
    op.drop_table('team_invitations')
    # ### end Alembic commands ###
