"""add indexes to events table

Revision ID: 9a32ba5b2aa1
Revises: e8175d1129f5
Create Date: 2025-07-15 13:38:25.733463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a32ba5b2aa1'
down_revision = 'e8175d1129f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_sender_id_type_name_timestamp', 'events', ['sender_id', 'type_name', 'timestamp'], unique=False)
    op.create_index('ix_events_timestamp', 'events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_timestamp', table_name='events')
    op.drop_index('ix_events_sender_id_type_name_timestamp', table_name='events')
    # ### end Alembic commands ###
