"""Add Team model and update FlaggedResponse for team functionality

Revision ID: 9bff59d2002e
Revises: 9d799fd2feea
Create Date: 2025-05-20 22:23:40.848846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bff59d2002e'
down_revision = '9d799fd2feea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('taskset_id', table_name='celery_tasksetmeta')
    op.drop_table('celery_tasksetmeta')
    op.drop_index('task_id', table_name='celery_taskmeta')
    op.drop_table('celery_taskmeta')
    op.add_column('flagged_responses', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('flagged_responses', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'flagged_responses', 'teams', ['team_id'], ['id'])
    op.add_column('teams', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint('teams_ibfk_1', 'teams', type_='foreignkey')
    op.drop_column('teams', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('teams_ibfk_1', 'teams', 'users', ['owner_id'], ['id'])
    op.drop_column('teams', 'description')
    op.drop_constraint(None, 'flagged_responses', type_='foreignkey')
    op.drop_column('flagged_responses', 'is_public')
    op.drop_column('flagged_responses', 'team_id')
    op.create_table('celery_taskmeta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(), nullable=True),
    sa.Column('traceback', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('args', sa.BLOB(), nullable=True),
    sa.Column('kwargs', sa.BLOB(), nullable=True),
    sa.Column('worker', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('retries', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', mysql.VARCHAR(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('task_id', 'celery_taskmeta', ['task_id'], unique=False)
    op.create_table('celery_tasksetmeta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taskset_id', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('taskset_id', 'celery_tasksetmeta', ['taskset_id'], unique=False)
    # ### end Alembic commands ###
