"""add_something_Im_not_sure

Revision ID: e8175d1129f5
Revises: 541c674cc1f6
Create Date: 2025-05-21 18:04:45.206070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8175d1129f5'
down_revision = '541c674cc1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flagged_responses', sa.Column('message_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flagged_responses', 'message_index')
    # ### end Alembic commands ###
